sudo: false

dist: trusty

cache: bundler

language: ruby

addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
      - google-chrome-stable
      - chromium-chromedriver

env:
  global:
    - PGUSER=travis
    - PGPORT=5433

before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  - bundle exec rails db:setup RAILS_ENV=test
  - bundle exec rspec spec
