sudo: false

dist: trusty

cache: bundler

language: ruby

addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

env:
  global:
    - PGUSER=travis
    - PGPORT=5433

before_script:
  - bundle exec rails db:setup RAILS_ENV=test
  - bundle exec rspec spec
